FROM golang:latest

ENV package github.com/larsha/go-template

ADD . /go/src/$package

WORKDIR /go/src/$package

RUN go get -t $package
RUN go get github.com/stretchr/testify/assert

WORKDIR /go

CMD go run src/$package/main.go
